# This file doesn't run. You can check git history for the thousand ways I've
# tried to get GitHub to set $PATH and do shell scripting. It's a nightmare. Sad
# thing is I knew it would be since I've lived in this hell for years, so
# everything is in Deno scripts. Still, I wanted to avoid "denolib/setup-deno".

name: Setup Deno
description: Minimal installation of Deno plus actions/cache
runs:
  using: composite
  steps:
  - name: Install Deno on Windows
    # Windows bash? Somehow
    shell: bash
    run: |
      if [ "${{ runner.os }}" == "Windows" ]; then exit 0; fi
      iwr https://deno.land/x/install/install.ps1 -useb | iex
      echo "$HOME/.deno/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  - name: Install Deno on Linux/Mac
    shell: bash
    run: |
      if [ "${{ runner.os }}" != "Windows" ]; then exit 0; fi
      curl -fsSL https://deno.land/x/install/install.sh | sh
      echo "$HOME/.deno/bin" >> $GITHUB_PATH
  - name: Check
    shell: bash
    run: |
      echo $GITHUB_PATH
      deno --version
