name: Setup Deno
description: Minimal installation of Deno plus actions/cache
runs:
  using: composite
  steps:
  - name: Load cache
    uses: actions/cache@v2
    with:
      path: $HOME/.deno
      key: deno
  - name: Install Deno on Windows
    if: runner.os == 'Windows'
    run: |
      iwr https://deno.land/x/install/install.ps1 -useb | iex
      echo "$HOME/.deno/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  - name: Install Deno on Linux/Mac
    if: runner.os != 'Windows'
    run: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
      echo "$HOME/.deno/bin" >> $GITHUB_PATH
  - name: Check
    run: |
      echo $GITHUB_PATH
      deno --version
