name: Setup Deno
description: Minimal installation of Deno plus actions/cache
runs:
  using: composite
  steps:
  - name: Install Deno on Windows
    # Windows bash? Somehow
    shell: bash
    run: |
      ${{ runner.os }} != 'Windows' && exit 0
      iwr https://deno.land/x/install/install.ps1 -useb | iex
      echo "$HOME/.deno/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  - name: Install Deno on Linux/Mac
    shell: bash
    run: |
      ${{ runner.os }} == 'Windows' && exit 0
      curl -fsSL https://deno.land/x/install/install.sh | sh
      echo "$HOME/.deno/bin" >> $GITHUB_PATH
  - name: Check
    shell: bash
    run: |
      echo $GITHUB_PATH
      deno --version
