name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  client-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node-version:
          - 15.x
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.os }} ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Node dependency cache
      uses: actions/cache@v2
      with:
        # Cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - run: npm ci
    - run: npm run build
    # - run: npm test
    - name: Archive client build
      uses: actions/upload-artifact@v2
      with:
        name: client-build
        # Even though this has "working-directory: client" it needs a full path...
        path: |
          client/build
          !client/build/**/*.map
  server-build:
    runs-on: ${{ matrix.os }}
    needs: client-build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Download the client files
      uses: actions/download-artifact@v2
      with:
        name: client-build
    - name: Windows Deno install
      if: matrix.os == 'windows-latest'
      run: |
        $env:DENO_INSTALL = "C:\Program Files\deno"
        iwr https://deno.land/x/install/install.ps1 -useb | iex
        deno --version
        dir
    - name: Nix Deno install
      if: matrix.os != 'windows-latest'
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh
        deno --version
        ls -l
    - name: Pass off to internal script
      run: deno run -A ./run.ts
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: localstar-binaries
        path: server/bin/**
